/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget { 'month' : string, 'amount' : number }
export interface Expense {
  'id' : bigint,
  'month' : string,
  'date' : string,
  'name' : string,
  'createdAt' : Time,
  'paymentMode' : string,
  'category' : string,
  'amount' : number,
}
export interface ExpenseUpdateData {
  'id' : bigint,
  'month' : string,
  'date' : string,
  'name' : string,
  'paymentMode' : string,
  'category' : string,
  'amount' : number,
}
export interface Investment {
  'id' : bigint,
  'month' : string,
  'date' : string,
  'createdAt' : Time,
  'notes' : [] | [string],
  'investmentType' : string,
  'amount' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<
    [string, number, string, string, string, string],
    bigint
  >,
  'addInvestment' : ActorMethod<
    [string, number, string, string, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteInvestment' : ActorMethod<[bigint], undefined>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllInvestments' : ActorMethod<[], Array<Investment>>,
  'getAllMonthsWithActivity' : ActorMethod<[], Array<string>>,
  'getBudgetByMonth' : ActorMethod<[string], [] | [Budget]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpensesByMonth' : ActorMethod<[string], Array<Expense>>,
  'getInvestmentsByMonth' : ActorMethod<[string], Array<Investment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBudget' : ActorMethod<[string, number], undefined>,
  'updateExpense' : ActorMethod<[ExpenseUpdateData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];