/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'paymentMode' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Investment = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'investmentType' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Budget = IDL.Record({
  'month' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExpenseUpdateData = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'paymentMode' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addInvestment' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
  'getAllMonthsWithActivity' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBudgetByMonth' : IDL.Func([IDL.Text], [IDL.Opt(Budget)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpensesByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getInvestmentsByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Investment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateExpense' : IDL.Func([ExpenseUpdateData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'paymentMode' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Investment = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'investmentType' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Budget = IDL.Record({ 'month' : IDL.Text, 'amount' : IDL.Float64 });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExpenseUpdateData = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'paymentMode' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addInvestment' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
    'getAllMonthsWithActivity' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBudgetByMonth' : IDL.Func([IDL.Text], [IDL.Opt(Budget)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpensesByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getInvestmentsByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Investment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateExpense' : IDL.Func([ExpenseUpdateData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };